import Head from 'next/head'
import DefaultTheme from "../styles/DefaultTheme";
import TopAppBar from "../components/TopAppBar";
import React from "react";
import {Button, Container, Grid, MuiThemeProvider} from "@material-ui/core";

const Home = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href={"/favicon.ico"}/>
            </Head>
            <main>
                <MuiThemeProvider theme={DefaultTheme}>
                    <TopAppBar/>
                    <Container>
                        <Grid container spacing={1} alignItems={"center"} justifyContent={"center"}>
                            <Grid item xs={3}>
                                <Button href={"/login"} fullWidth>
                                    Anmelden
                                </Button>
                            </Grid>
                            <Grid item xs={3}>
                                <Button href={"/register"} fullWidth>
                                    Registrieren
                                </Button>
                            </Grid>
                        </Grid>
                    </Container>
                </MuiThemeProvider>
            </main>
        </div>
    )
}
export default Home

