import Head from 'next/head'
import DefaultTheme from "../styles/DefaultTheme";
import TopAppBar from "../components/TopAppBar";
import React from "react";
import {MuiThemeProvider} from "@material-ui/core";
import LoginForm from "../components/LoginForm";

const login = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href={"/favicon.ico"}/>
            </Head>
            <main>
                <MuiThemeProvider theme={DefaultTheme}>
                    <TopAppBar/>
                    <LoginForm/>
                </MuiThemeProvider>
            </main>
        </div>
    )
}
export default login

