import Head from 'next/head'
import RegisterForm from "../components/RegisterForm";
import DefaultTheme from "../styles/DefaultTheme";
import TopAppBar from "../components/TopAppBar";
import React from "react";
import {MuiThemeProvider} from "@material-ui/core";

const register = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href={"/favicon.ico"}/>
            </Head>
            <main>
                <MuiThemeProvider theme={DefaultTheme}>
                    <TopAppBar/>
                    <RegisterForm/>
                </MuiThemeProvider>
            </main>
        </div>
    )
}
export default register

